@Odonto.API_HostAddress = https://localhost:7120
@Token = informe-o-token-retornado-pelo-login

GET {{Odonto.API_HostAddress}}/api/me
Accept: application/json
Authorization: Bearer {{Token}}

###

PATCH {{Odonto.API_HostAddress}}/api/me
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "nomeExibicao": "Fábio",
  "telefone": "81999999999"
}

###

GET {{Odonto.API_HostAddress}}/api/me/foto
Authorization: Bearer {{Token}}

###

DELETE {{Odonto.API_HostAddress}}/api/me/foto
Authorization: Bearer {{Token}}
